---
  output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: console
---
  
  ```{r}
source('setup.R')
```

```{r}
rm(list=ls())
library(ggplot2)
library(knitr)
library(RColorBrewer)
library(tidyverse)
library(latex2exp)
library(car)
```

# Problem A
```{r}
df1=read.csv(file="./Data/clothingFull.csv")
df2=read.csv(file="./Data/clothingSum.csv")
df2$subjId=as.character(df2$subjId)
df1$obs.no=as.character(df1$obs.no)
df1$subjId=as.character(df1$subjId)
names(df2)[5]="tIn"
names(df1)[4]="tIn"
str(df1)

str(df2)

```

```{r}
ggplot(df2,aes(x=tOut,y=clo))+geom_point()+facet_wrap(~sex)

ggplot(df2,aes(x=tOut,y=tIn))+geom_point()+facet_wrap(~sex)

ggplot(df2,aes(x=tOut,y=tIn))+geom_point()+facet_wrap(~sex)
X=cbind(1,1:10,rnorm(10))
xl=c()
solve(t(X)%*%X)
ggplot(df2,aes(x=day,y=clo))+geom_point()
ggplot(df2,aes(x=day,y=tOut))+geom_point()
ggplot(df2,aes(x=tIn,y=clo,col=sex))+geom_point()+facet_wrap(~day)
ggplot(df2,aes(x=tIn,y=clo,col=sex))+geom_point()+facet_wrap(~day)


df2$subjId=as.character(df2$subjId)
ggplot(df2,aes(x=tOut,y=clo,group=subjId,col=subjId))+
  geom_text(aes(label=day))+geom_path()+facet_wrap(~sex)+
  theme(legend.position = "none")+
  xlab("Outdoor temperature")+ylab("Clothing")
ggplot(df2,aes(x=tIn,y=clo,group=subjId,col=subjId))+
  geom_text(aes(label=day))+geom_path()+facet_wrap(~sex)+
  theme(legend.position = "none")+
  xlab("Indoor temperature")+ylab("Clothing")


df2$day=as.factor(df2$day)
df2$subjId=as.factor(df2$subjId)
ggplot(df2,aes(x=tOut,y=clo,col=subjId))+geom_point()+geom_line()+facet_wrap(~sex)
ggplot(df2,aes(x=tIn,y=clo,col=subjId))+geom_point()+geom_line()+facet_wrap(~sex)+
  theme(legend)

ggplot(df2,aes(x=tOut-tIn,y=clo,col=subjId))+geom_point()+geom_line()+facet_wrap(~sex)

ggplot(df2,aes(x=tOut,y=tIn,col=subjId))+geom_point()+geom_line()
ggplot(df2,aes(x=tIn))+geom_histogram()

```

```{r}
df1$obs.no=as.character(df1$obs.no)
df1$subjId=as.character(df1$subjId)
ggplot(df1,aes(x=tOut,y=clo,group=subjId,col=subjId))+
  geom_text(aes(label=obs.no))+geom_path()+facet_grid(cols=vars(sex),rows=vars(day))+
  theme(legend.position = "none")+
  xlab("Outdoor temperature")+ylab("Clothing")
```

Temperature is almost a gaussian distribution
Indoor temperature is obviously higher
Somewhat relation between indoor and outdoor temperature. 

Temperature vs Clo shows that males use a more constant amount of clothing, while female amount of clothing decrease as the temperature increases. 

```{r}
# Backwards selection
fit1=lm(clo~ tOut*tIn*sex,data=df2)
ridge=glmnet(df2$clo,df2[,4:6],alpha=0,family='gaussian',)
Anova(fit1,type=3)
summary(fit1)
anova(fit1)
# We are removing the indoor and outdoor temperature interaction
fit2=lm(clo~ tOut+tIn+tOut*sex+tIn*sex,data=df2)
summary(fit2)

fit2=lm(clo~ tOut+tIn+tOut*sex+tIn*sex,data=df2)
summary(fit2)
fit3=lm(clo~ tOut+tIn+tIn:sex+sex,data=df2)
df2$resid_fit3=rstudent(fit3)
ggplot(df2,aes(x=resid_fit3))+geom_histogram()+facet_wrap(~sex)
ggplot(df2,aes(x=resid_fit3))+geom_histogram()+facet_wrap(~sex)

fit3=lm(clo~ tOut+tIn+tIn:sex+sex,data=df2)

summary(fit3)

hist(resid(fit3),nclass=20)
hist(rstudent(fit3),nclass=20)
qqnorm(resid(fit3)[df2$sex=="male"])
qqline(resid(fit3)[df2$sex=="male"])
qqnorm(rstudent(fit3)[df2$sex=="male"])
qqline(rstudent(fit3)[df2$sex=="male"])

qqnorm(resid(fit3)[df2$sex=="female"])
qqline(resid(fit3)[df2$sex=="female"])
qqnorm(rstudent(fit3)[df2$sex=="female"])
qqline(rstudent(fit3)[df2$sex=="female"])

fit4=lm(clo~ tOut+tIn+sex,data=df2)
summary(fit4)
hist(resid(fit4),nclass=20)
qqnorm(resid(fit4))
qqline(resid(fit4))

library(lme4)
anova(fit4,fit3,test = 'LRT')
anova(fit4,fit3,test = 'LRT')

df2$trans=log(df2$clo/(1-df2$clo))
ggplot(df2,aes(x=tOut,y=trans))+geom_point()+facet_wrap(~sex)

ggplot(df2,aes(x=tIn,y=trans))+geom_point()+facet_wrap(~sex)


# Backwards selection
fit1=lm(trans~ tOut*tIn*sex,data=df2)
summary(fit1)
# We are removing the indoor and outdoor temperature interaction
fit2=lm(trans~ tOut+tIn+tOut*sex+tIn*sex,data=df2)
summary(fit2)

fit3=lm(trans~ tOut+tIn+tIn:sex+sex,data=df2)
summary(fit3)
df2$resid_fit3=resid(fit3)
df2$resid_fit3
ggplot(df2,aes(x=sex,y=resid_fit3))+geom_boxplot()
str(df2)
hist(resid(fit3),nclass=20)
qqnorm(resid(fit3))
qqline(resid(fit3))

fit4=lm(trans~ tOut+tIn+sex,data=df2)
summary(fit4)
hist(resid(fit4),nclass=20)
qqnorm(resid(fit4))
qqline(resid(fit4))


# Backwards selection
fitm1=lm(clo~ tOut*tIn,data=df2[df2$sex=="male",])
summary(fitm1)


fitm2=lm(clo~ -1+tOut*tIn,data=df2[df2$sex=="male",])
summary(fitm2)
hist(resid(fitm2))
qqnorm((resid(fitm2)))
qqline((resid(fitm2)))

# Backwards selection
fitf1=lm(clo~ tOut*tIn,data=df2[df2$sex=="female",])
summary(fitf1)

fitf2=lm(clo~ tOut+tIn,data=df2[df2$sex=="female",])
summary(fitf2)

hist(resid(fitf2))
qqnorm((resid(fitf2)))
qqline((resid(fitf2)))

# We are removing the indoor and outdoor temperature interaction
fit2=lm(clo~ tOut+tIn+tOut*sex+tIn*sex,data=df2)
summary(fit2)

fit2=lm(clo~ tOut+tIn+tOut*sex+tIn*sex,data=df2)
summary(fit2)
fit3=lm(clo~ tOut+tIn+tIn:sex+sex,data=df2)
summary(fit3)
hist(resid(fit3),nclass=20)
qqnorm(resid(fit3))
qqline(resid(fit3))

```

```{r}
# part A.4

ll_partA<-function(a,data=df2){
  weights=rep(1,nrow(data))
  weights[data$sex=="female"]=1/a
  fit=lm(clo~ tOut+tIn+tIn:sex+sex,w=weights,data=data)
  return(logLik(fit))
}
weighted_lm<-function(a,data=df2){
  weights=rep(1,nrow(data))
  weights[data$sex=="female"]=1/a
  fit=lm(clo~ tOut+tIn+tIn:sex+sex,w=weights,data=data)
  return(fit)
}
# Finding optimal weights
opt=optim(1,ll_partA,control=list(fnscale=-1),hessian=T)
# Fitting model with optimal weights
fit=weighted_lm(opt$par)
Anova(fit,type=2)
# CI, NOT  profile log-likelihood -> we need to add one for the weights
confint(fit)
cbind(lower=coef(fit)+qt(0.025,df=fit$df.residual)*sqrt(diag(vcov(fit))),
      upper=coef(fit)+qt(0.975,df=fit$df.residual)*sqrt(diag(vcov(fit))))
# profile log-Likelihood plotting
a_list=seq(1.7,5,0.001)
ll_list=sapply(a_list,ll_partA)
plot(a_list,ll_list-max(ll_list),main="profile Likelihood of weights",type="l")
abline(h=-0.5*qchisq(0.95,df=1),col=4,lwd=2)
# Finding intercepts
idx_l=which((ll_list[-length(ll_list)]-max(ll_list) < -0.5*qchisq(0.95,df=1)&ll_list[-1]-max(ll_list)> -0.5*qchisq(0.95,df=1)))
idx_h=which((ll_list[-length(ll_list)]-max(ll_list) > -0.5*qchisq(0.95,df=1)&ll_list[-1]-max(ll_list)< -0.5*qchisq(0.95,df=1)))
# Full model profile LL
m=confint(fit)
m=rbind(m,weights=c(a_list[idx_l],a_list[idx_h]))
m
opt$par+c(-1,1)*sqrt(diag(solve(-opt$hessian)))*qt(0.975,df=fit$df.residual)
# Conf int for sigma
lm_sigma_conf<-function(fit,CI=0.95){
  # Book page 53: sigma_hat^2~sigma^2*chisq_f/f where f=n-k
  # rearanging: sigma_hat^2*f/chisq_f
  sigma=sigma(fit)
  d_f=fit$df.residual
  conf_sigma2=d_f*sigma^2/qchisq(c((1-CI)/2,1-(1-CI)/2), df = d_f, lower.tail = FALSE)
  conf=sqrt(conf_sigma2)
  names(conf)=paste(c((1-CI)/2,1-(1-CI)/2)*100,"%")
  return(conf)
}
# Conf int for sigma
lm_sigma_conf(fit)


```


```{r}
# Backwards selection
fit1=lm(clo~ diff+sex+sex:diff,data=df2)
summary(fit1)
# We are removing the indoor and outdoor temperature interaction
fit2=lm(clo~ diff+sex:diff,data=df2)
summary(fit2)

hist(resid(fit2),nclass=20)
qqnorm(resid(fit2)[df2$sex=="male"])
qqline(resid(fit2)[df2$sex=="male"])

qqnorm(resid(fit2)[df2$sex=="female"])
qqline(resid(fit2)[df2$sex=="female"])


qqnorm(resid(fit2))
qqline(resid(fit2))

```



```{r}
df3=read.csv(file="./Data/clothingSum.csv")
df3=df3[,3:6]
df3=df3[-(1:nrow(df3)),]
df3
mean(df2$tIn)
tmp_male=data.frame(clo=NA,tOut=seq(min(df2$tOut),max(df2$tOut),0.1),tIn=mean(df2$tIn),sex="male")
tmp_female=data.frame(clo=NA,tOut=seq(min(df2$tOut),max(df2$tOut),0.1),tIn=mean(df2$tIn),sex="female")
df3=rbind(tmp_male,tmp_female)
df3=rbind(df3,)

```

```{r}
sum(df2$sex=="male")
sum(df2$sex=="female")

df3=df2
tmp=df2

df3$clo2=df3$clo
df3$clo[df3$sex=="male"]=NA
df3$clo2[df3$sex=="female"]=NA

tmp$clo2=tmp$clo
tmp$clo[tmp$sex=="female"]=NA
tmp$clo2[tmp$sex=="male"]=NA

df3=rbind(df3,tmp)
X=as.matrix(df3[,4:5])
Y=as.matrix(df3[,c(3,7)])
matrix(c())
solve(t(X)%*%X,t(X)%*%Y)
lm(cbind(clo,clo2)~tIn+tOut,data=df3)
str(df2)

```

```{r}
fit=lm(clo ~ tOut*tIn*sex+subjId,data=df2)
summary(fit)

fit=lm(clo ~ tOut+tIn+sex+tIn:sex+tOut:sex+tIn:tOut+subjId,data=df2)
summary(fit)

fit=lm(clo ~ tOut+tIn+sex+tIn:sex+tIn:tOut+subjId,data=df2)
summary(fit)

fit=lm(clo ~ tOut+tIn+sex+tIn:sex+subjId,data=df2)
summary(fit)

fit=lm(clo ~ tOut+tIn+subjId,data=df2)
summary(fit)

library(lme4)
library(lmerTest)
fit_mixed=lmer(clo ~ tIn*tOut*sex+(1|subjId),data=df2)
summary(fit_mixed)

fit_mixed=lmer(clo ~ tIn+tOut+sex+tOut:tIn+tOut:sex+tIn:sex+(1|subjId),data=df2)
summary(fit_mixed)

fit_mixed=lmer(clo ~ tIn+tOut+sex+tOut:sex+tIn:sex+(1|subjId),data=df2)
summary(fit_mixed)

fit_mixed=lmer(clo ~ tIn+tOut+sex+tIn:sex+(1|subjId),data=df2)
summary(fit_mixed)

ggplot(data = data.frame(c()))+
  stat_qq(aes(sample=resid(fit_mixed)))+
  stat_qq_line(aes(sample=resid(fit_mixed)))

  stat_qq_line(aes(sample=resid(fit_mixed)))

ranef(fit_mixed)
hist(ranef(fit_mixed)$subjId[,1])


qqnorm(ranef(fit_mixed)$subjId[,1])
qqline(ranef(fit_mixed)$subjId[,1])

 fixef(fit_mixed)

qqnorm(resid(fit_mixed))
qqline(resid(fit_mixed))



```

```{r}
#----------------
# part C
fit3=lm(clo~ tOut+tIn+tIn:sex+sex,data=df1)
summary(fit3)
df1$resid=resid(fit3)
df1$student=rstudent(fit3)
ggplot(df1,aes(x=tOut,y=student,group=subjId,col=subjId))+
  geom_text(aes(label=obs.no))+geom_path()+facet_grid(cols=vars(sex),rows=vars(day))+
  theme(legend.position = "none")+
  xlab("Outdoor temperature")+ylab("Clothing")
ggplot(df1,aes(x=tIn,y=student,group=subjId,col=subjId))+
  geom_text(aes(label=obs.no))+geom_path()+facet_grid(cols=vars(sex),rows=vars(day))+
  theme(legend.position = "none")+
  xlab("Indoor temperature")+ylab("Clothing")

# from part B
fit3B = lm( clo ~ tOut+subjId,data = df1)
summary(fit3B)
df1$resid=resid(fit3B)
df1$student=rstudent(fit3B)
ggplot(df1,aes(x=tOut,y=student,group=subjId,col=subjId))+
  geom_text(aes(label=obs.no))+geom_path()+facet_grid(cols=vars(sex),rows=vars(day))+
  theme(legend.position = "none")+
  xlab("Outdoor temperature")+ylab("Residuals")

ggplot(df1,aes(x=tIn,y=student,group=subjId,col=subjId))+
  geom_text(aes(label=obs.no))+geom_path()+facet_grid(cols=vars(sex),rows=vars(day))+
  theme(legend.position = "none")+
  xlab("Indoor temperature")+ylab("Residuals")


#-------------
```




